site_name: FAIR Documentation
site_description: >-
  Lightweight documentation for the FAIR platform with multilingual support.
site_dir: site
docs_dir: docs
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Release Automation: development/releases.md
plugins:
  - search
  - i18n:
      docs_structure: folder
      default_language: en
      languages:
        - locale: en
          name: English
          build: true
        - locale: es
          name: Español
          build: true
      nav_translations:
        es:
          Home: Inicio
          Getting Started: Primeros Pasos
          Release Automation: Automatización de lanzamientos
theme:
  name: mkdocs
  language: en
  features:
    - navigation.tabs
    - navigation.top
extra:
  alternate:
    - name: English
      link: /docs/
      lang: en
    - name: Español
      link: /docs/es/
      lang: es
