"""Create the explicit FAIR v2 Phase 1 foundation.

Revision ID: 20260711_0017
Revises: 20260307_0013
Create Date: 2026-07-11 19:45:25.462892
"""

from __future__ import annotations

from alembic import op  # type: ignore
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "20260711_0017"
down_revision = "20260307_0013"
branch_labels = None
depends_on = None


def _create_immutability_guards() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            sa.text("""
        CREATE FUNCTION fair_reject_terminal_artifact_version_mutation()
        RETURNS trigger AS $$ BEGIN
          IF OLD.state IN ('finalized', 'abandoned') THEN
            RAISE EXCEPTION 'terminal ArtifactVersion % is immutable', OLD.id;
          END IF;
          RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
        END; $$ LANGUAGE plpgsql;
        CREATE TRIGGER fair_artifact_version_immutable
        BEFORE UPDATE OR DELETE ON artifact_versions
        FOR EACH ROW EXECUTE FUNCTION fair_reject_terminal_artifact_version_mutation();
        CREATE FUNCTION fair_reject_terminal_artifact_part_mutation()
        RETURNS trigger AS $$ BEGIN
          IF EXISTS (SELECT 1 FROM artifact_versions
                     WHERE id = OLD.artifact_version_id
                       AND state IN ('finalized', 'abandoned')) THEN
            RAISE EXCEPTION 'parts of terminal ArtifactVersion % are immutable', OLD.artifact_version_id;
          END IF;
          RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
        END; $$ LANGUAGE plpgsql;
        CREATE TRIGGER fair_artifact_part_immutable
        BEFORE UPDATE OR DELETE ON artifact_parts
        FOR EACH ROW EXECUTE FUNCTION fair_reject_terminal_artifact_part_mutation();
        """)
        )
    else:
        for statement in (
            "CREATE TRIGGER fair_artifact_version_immutable_update BEFORE UPDATE ON artifact_versions WHEN OLD.state IN ('finalized','abandoned') BEGIN SELECT RAISE(ABORT, 'terminal ArtifactVersion is immutable'); END",
            "CREATE TRIGGER fair_artifact_version_immutable_delete BEFORE DELETE ON artifact_versions WHEN OLD.state IN ('finalized','abandoned') BEGIN SELECT RAISE(ABORT, 'terminal ArtifactVersion is immutable'); END",
            "CREATE TRIGGER fair_artifact_part_immutable_update BEFORE UPDATE ON artifact_parts WHEN EXISTS (SELECT 1 FROM artifact_versions WHERE id=OLD.artifact_version_id AND state IN ('finalized','abandoned')) BEGIN SELECT RAISE(ABORT, 'parts of terminal ArtifactVersion are immutable'); END",
            "CREATE TRIGGER fair_artifact_part_immutable_delete BEFORE DELETE ON artifact_parts WHEN EXISTS (SELECT 1 FROM artifact_versions WHERE id=OLD.artifact_version_id AND state IN ('finalized','abandoned')) BEGIN SELECT RAISE(ABORT, 'parts of terminal ArtifactVersion are immutable'); END",
        ):
            op.execute(sa.text(statement))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extension_installations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("extension_id", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("version", sa.String(length=128), nullable=True),
        sa.Column("dispatch_url", sa.Text(), nullable=True),
        sa.Column("health_url", sa.Text(), nullable=True),
        sa.Column("manifest_version", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "manifest",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "extension_id", name="uq_extension_installations_extension_id"
        ),
    )
    op.create_table(
        "capability_definitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("installation_id", sa.UUID(), nullable=False),
        sa.Column("capability_id", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("input_schema_uri", sa.String(length=2048), nullable=True),
        sa.Column("output_schema_uri", sa.String(length=2048), nullable=True),
        sa.Column("config_schema_uri", sa.String(length=2048), nullable=True),
        sa.Column(
            "requested_scopes",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "declared_effects",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("supports_streaming", sa.Boolean(), nullable=False),
        sa.Column("supports_cancellation", sa.Boolean(), nullable=False),
        sa.Column("supports_resume", sa.Boolean(), nullable=False),
        sa.Column("supports_batch", sa.Boolean(), nullable=False),
        sa.Column(
            "manifest_snapshot",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["installation_id"], ["extension_installations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "installation_id",
            "capability_id",
            "version",
            name="uq_capability_definitions_installation_identity",
        ),
    )
    op.create_index(
        "ix_capability_definitions_lookup",
        "capability_definitions",
        ["capability_id", "version"],
        unique=False,
    )
    op.create_table(
        "flows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_flows_owner_archived",
        "flows",
        ["owner_user_id", "archived_at"],
        unique=False,
    )
    op.create_table(
        "extension_grants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("installation_id", sa.UUID(), nullable=False),
        sa.Column("capability_definition_id", sa.UUID(), nullable=True),
        sa.Column("course_id", sa.UUID(), nullable=True),
        sa.Column("assignment_id", sa.UUID(), nullable=True),
        sa.Column("effect", sa.String(length=128), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("granted_by_user_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignment_id"], ["assignments.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["capability_definition_id"],
            ["capability_definitions.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["installation_id"], ["extension_installations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "installation_id",
            "capability_definition_id",
            "course_id",
            "assignment_id",
            "effect",
            name="uq_extension_grants_scope_effect",
        ),
    )
    op.create_index(
        "ix_extension_grants_resolution",
        "extension_grants",
        ["installation_id", "course_id", "assignment_id", "effect"],
        unique=False,
    )
    op.create_table(
        "flow_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("flow_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column(
            "definition",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "capability_pins",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "config_snapshot",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("definition_hash", sa.String(length=128), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["flow_id"], ["flows.id"], ondelete="RESTRICT"),
        sa.CheckConstraint("ordinal >= 1", name="ck_flow_versions_ordinal_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("flow_id", "ordinal", name="uq_flow_versions_flow_ordinal"),
    )
    op.create_index(
        "ix_flow_versions_published",
        "flow_versions",
        ["flow_id", "state", "published_at"],
        unique=False,
    )
    op.create_table(
        "threads",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=True),
        sa.Column("assignment_id", sa.UUID(), nullable=True),
        sa.Column("submission_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignment_id"], ["assignments.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["submissions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "turns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("client_request_id", sa.String(length=255), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("ordinal >= 1", name="ck_turns_ordinal_positive"),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "thread_id", "client_request_id", name="uq_turns_thread_request"
        ),
        sa.UniqueConstraint("thread_id", "ordinal", name="uq_turns_thread_ordinal"),
    )
    op.create_table(
        "executions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=True),
        sa.Column("turn_id", sa.UUID(), nullable=True),
        sa.Column("parent_execution_id", sa.UUID(), nullable=True),
        sa.Column("root_execution_id", sa.UUID(), nullable=False),
        sa.Column("retry_of_execution_id", sa.UUID(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("capability_id", sa.String(length=255), nullable=True),
        sa.Column("capability_version", sa.String(length=128), nullable=True),
        sa.Column("flow_version_id", sa.UUID(), nullable=True),
        sa.Column("flow_node_id", sa.String(length=255), nullable=True),
        sa.Column("initiated_by_user_id", sa.UUID(), nullable=True),
        sa.Column("extension_installation_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("waiting_reason", sa.String(length=255), nullable=True),
        sa.Column(
            "input",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "output_summary",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "cancellation_requested_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("trace_id", sa.String(length=128), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.CheckConstraint("attempt >= 1", name="ck_executions_attempt_positive"),
        sa.CheckConstraint(
            "id != parent_execution_id", name="ck_executions_no_self_parent"
        ),
        sa.CheckConstraint(
            "id != retry_of_execution_id", name="ck_executions_no_self_retry"
        ),
        sa.ForeignKeyConstraint(
            ["extension_installation_id"],
            ["extension_installations.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["flow_version_id"], ["flow_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["initiated_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["parent_execution_id"], ["executions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["retry_of_execution_id"], ["executions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["root_execution_id"], ["executions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["turn_id"], ["turns.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_executions_root_created",
        "executions",
        ["root_execution_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_executions_status_created",
        "executions",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_executions_thread_created",
        "executions",
        ["thread_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "artifact_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("artifact_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("media_type", sa.String(length=255), nullable=True),
        sa.Column("schema_uri", sa.String(length=2048), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("created_by_extension_installation_id", sa.UUID(), nullable=True),
        sa.Column("producing_execution_id", sa.UUID(), nullable=True),
        sa.Column("hash_algorithm", sa.String(length=32), nullable=True),
        sa.Column("content_hash", sa.String(length=128), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("supersedes_version_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("abandoned_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "ordinal >= 1", name="ck_artifact_versions_ordinal_positive"
        ),
        sa.CheckConstraint(
            "size_bytes IS NULL OR size_bytes >= 0",
            name="ck_artifact_versions_size_nonnegative",
        ),
        sa.CheckConstraint(
            "state = 'draft' OR (hash_algorithm IS NOT NULL AND content_hash IS NOT NULL AND size_bytes IS NOT NULL)",
            name="ck_artifact_versions_terminal_integrity",
        ),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["created_by_extension_installation_id"],
            ["extension_installations.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["producing_execution_id"], ["executions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_version_id"], ["artifact_versions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "artifact_id", "ordinal", name="uq_artifact_versions_artifact_ordinal"
        ),
    )
    op.create_index(
        "ix_artifact_versions_artifact_state",
        "artifact_versions",
        ["artifact_id", "state"],
        unique=False,
    )
    op.create_index(
        "ix_artifact_versions_producer",
        "artifact_versions",
        ["producing_execution_id"],
        unique=False,
    )
    op.create_table(
        "execution_dispatch_outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column("command_kind", sa.String(length=32), nullable=False),
        sa.Column("job_id", sa.String(length=255), nullable=False),
        sa.Column("target", sa.String(length=255), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_by", sa.String(length=255), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"], ["executions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", name="uq_dispatch_outbox_job_id"),
    )
    op.create_index(
        "ix_dispatch_outbox_claim",
        "execution_dispatch_outbox",
        ["status", "available_at"],
        unique=False,
    )
    op.create_table(
        "execution_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("producer_source", sa.String(length=255), nullable=False),
        sa.Column("producer_event_id", sa.String(length=255), nullable=False),
        sa.Column("producer_sequence", sa.BigInteger(), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=False),
        sa.Column("schema_uri", sa.String(length=2048), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("visibility", sa.String(length=32), nullable=False),
        sa.Column("durability", sa.String(length=32), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("parent_event_id", sa.UUID(), nullable=True),
        sa.Column("trace_id", sa.String(length=128), nullable=True),
        sa.Column("span_id", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "sequence >= 1", name="ck_execution_events_sequence_positive"
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"], ["executions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_event_id"], ["execution_events.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "execution_id", "sequence", name="uq_execution_events_execution_sequence"
        ),
        sa.UniqueConstraint(
            "producer_source",
            "producer_event_id",
            name="uq_execution_events_producer_identity",
        ),
    )
    op.create_index(
        "ix_execution_events_replay",
        "execution_events",
        ["execution_id", "sequence"],
        unique=False,
    )
    op.create_index(
        "ix_execution_events_trace", "execution_events", ["trace_id"], unique=False
    )
    op.create_index(
        "ix_execution_events_type_time",
        "execution_events",
        ["execution_id", "type", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "execution_legacy_refs",
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("legacy_id", sa.String(length=255), nullable=False),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"], ["executions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("execution_id", "source_type"),
        sa.UniqueConstraint(
            "source_type", "legacy_id", name="uq_execution_legacy_refs_identity"
        ),
    )
    op.create_table(
        "execution_snapshots",
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column("last_sequence", sa.BigInteger(), nullable=False),
        sa.Column("reducer_version", sa.String(length=64), nullable=False),
        sa.Column(
            "projection",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"], ["executions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("execution_id"),
    )
    op.create_table(
        "interaction_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column(
            "schema",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "choices",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("target_url", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("requested_by_extension_installation_id", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "response",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"], ["executions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_extension_installation_id"],
            ["extension_installations.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_interaction_requests_execution_status",
        "interaction_requests",
        ["execution_id", "status"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("turn_id", sa.UUID(), nullable=True),
        sa.Column("producing_execution_id", sa.UUID(), nullable=True),
        sa.Column("parent_message_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("author_type", sa.String(length=32), nullable=False),
        sa.Column("author_user_id", sa.UUID(), nullable=True),
        sa.Column("author_extension_installation_id", sa.UUID(), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("ordinal >= 1", name="ck_messages_ordinal_positive"),
        sa.ForeignKeyConstraint(
            ["author_extension_installation_id"],
            ["extension_installations.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["author_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["parent_message_id"], ["messages.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["producing_execution_id"], ["executions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["turn_id"], ["turns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("turn_id", "ordinal", name="uq_messages_turn_ordinal"),
    )
    op.create_index(
        "ix_messages_thread_created",
        "messages",
        ["thread_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "artifact_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("artifact_version_id", sa.UUID(), nullable=False),
        sa.Column("relationship", sa.String(length=32), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("created_by_execution_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["artifact_version_id"], ["artifact_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_execution_id"], ["executions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "artifact_version_id",
            "relationship",
            "target_type",
            "target_id",
            name="uq_artifact_links_edge",
        ),
    )
    op.create_index(
        "ix_artifact_links_relationship",
        "artifact_links",
        ["relationship", "target_type"],
        unique=False,
    )
    op.create_index(
        "ix_artifact_links_target",
        "artifact_links",
        ["target_type", "target_id"],
        unique=False,
    )
    op.create_table(
        "artifact_parts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("artifact_version_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("media_type", sa.String(length=255), nullable=False),
        sa.Column("schema_uri", sa.String(length=2048), nullable=True),
        sa.Column("storage_uri", sa.Text(), nullable=True),
        sa.Column(
            "inline_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("hash_algorithm", sa.String(length=32), nullable=True),
        sa.Column("content_hash", sa.String(length=128), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column(
            "annotations",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("ordinal >= 1", name="ck_artifact_parts_ordinal_positive"),
        sa.CheckConstraint(
            "size_bytes IS NULL OR size_bytes >= 0",
            name="ck_artifact_parts_size_nonnegative",
        ),
        sa.CheckConstraint(
            "(storage_uri IS NOT NULL AND inline_json IS NULL) OR (storage_uri IS NULL AND inline_json IS NOT NULL)",
            name="ck_artifact_parts_exactly_one_source",
        ),
        sa.ForeignKeyConstraint(
            ["artifact_version_id"], ["artifact_versions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "artifact_version_id", "name", name="uq_artifact_parts_version_name"
        ),
        sa.UniqueConstraint(
            "artifact_version_id", "ordinal", name="uq_artifact_parts_version_ordinal"
        ),
    )
    op.create_index(
        "ix_artifact_parts_version_ordinal",
        "artifact_parts",
        ["artifact_version_id", "ordinal"],
        unique=False,
    )
    op.create_table(
        "grade_proposals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("proposal_ordinal", sa.Integer(), nullable=False),
        sa.Column("rubric_id", sa.UUID(), nullable=True),
        sa.Column("rubric_version", sa.Integer(), nullable=True),
        sa.Column(
            "rubric_snapshot",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "score",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("feedback_artifact_version_id", sa.UUID(), nullable=True),
        sa.Column("producing_execution_id", sa.UUID(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("created_by_extension_installation_id", sa.UUID(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "flags",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("supersedes_proposal_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_extension_installation_id"],
            ["extension_installations.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["feedback_artifact_version_id"],
            ["artifact_versions.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["producing_execution_id"], ["executions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["rubric_id"], ["rubrics.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["submissions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_proposal_id"], ["grade_proposals.id"], ondelete="RESTRICT"
        ),
        sa.CheckConstraint(
            "proposal_ordinal >= 1", name="ck_grade_proposals_ordinal_positive"
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="ck_grade_proposals_confidence_range",
        ),
        sa.CheckConstraint(
            "NOT (created_by_user_id IS NOT NULL AND created_by_extension_installation_id IS NOT NULL)",
            name="ck_grade_proposals_single_actor",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "submission_id",
            "proposal_ordinal",
            name="uq_grade_proposals_submission_ordinal",
        ),
    )
    op.create_index(
        "ix_grade_proposals_producing_execution",
        "grade_proposals",
        ["producing_execution_id"],
        unique=False,
    )
    op.create_index(
        "ix_grade_proposals_submission_status",
        "grade_proposals",
        ["submission_id", "status"],
        unique=False,
    )
    op.create_table(
        "message_parts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("part_type", sa.String(length=64), nullable=False),
        sa.Column("media_type", sa.String(length=255), nullable=True),
        sa.Column("schema_uri", sa.String(length=2048), nullable=True),
        sa.Column("text_content", sa.Text(), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("artifact_version_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("ordinal >= 1", name="ck_message_parts_ordinal_positive"),
        sa.ForeignKeyConstraint(
            ["artifact_version_id"], ["artifact_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "message_id", "ordinal", name="uq_message_parts_message_ordinal"
        ),
    )
    op.create_table(
        "grade_decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("proposal_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("decided_by_user_id", sa.UUID(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column(
            "selected_score",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("selected_feedback_artifact_version_id", sa.UUID(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"], ["grade_proposals.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["selected_feedback_artifact_version_id"],
            ["artifact_versions.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["submissions.id"], ondelete="RESTRICT"
        ),
        sa.CheckConstraint(
            "action != 'manual_replace' OR (selected_score IS NOT NULL OR selected_feedback_artifact_version_id IS NOT NULL)",
            name="ck_grade_decisions_manual_replacement_content",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_grade_decisions_proposal", "grade_decisions", ["proposal_id"], unique=False
    )
    op.create_index(
        "ix_grade_decisions_submission_created",
        "grade_decisions",
        ["submission_id", "created_at"],
        unique=False,
    )
    op.add_column(
        "artifacts", sa.Column("kind_uri", sa.String(length=2048), nullable=True)
    )
    op.add_column("artifacts", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("artifacts", sa.Column("owner_user_id", sa.UUID(), nullable=True))
    op.add_column(
        "artifacts", sa.Column("sensitivity", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "artifacts",
        sa.Column(
            "access_policy",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "artifacts", sa.Column("current_version_id", sa.UUID(), nullable=True)
    )
    with op.batch_alter_table("artifacts") as batch_op:
        batch_op.create_foreign_key(
            "fk_artifacts_owner_user_id",
            "users",
            ["owner_user_id"],
            ["id"],
            ondelete="RESTRICT",
        )
    _create_immutability_guards()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            sa.text(
                "DROP TRIGGER IF EXISTS fair_artifact_part_immutable ON artifact_parts"
            )
        )
        op.execute(
            sa.text(
                "DROP TRIGGER IF EXISTS fair_artifact_version_immutable ON artifact_versions"
            )
        )
        op.execute(
            sa.text(
                "DROP FUNCTION IF EXISTS fair_reject_terminal_artifact_part_mutation()"
            )
        )
        op.execute(
            sa.text(
                "DROP FUNCTION IF EXISTS fair_reject_terminal_artifact_version_mutation()"
            )
        )
    else:
        for name in (
            "fair_artifact_part_immutable_delete",
            "fair_artifact_part_immutable_update",
            "fair_artifact_version_immutable_delete",
            "fair_artifact_version_immutable_update",
        ):
            op.execute(sa.text(f"DROP TRIGGER IF EXISTS {name}"))
    with op.batch_alter_table("artifacts") as batch_op:
        batch_op.drop_constraint("fk_artifacts_owner_user_id", type_="foreignkey")
    op.drop_column("artifacts", "current_version_id")
    op.drop_column("artifacts", "access_policy")
    op.drop_column("artifacts", "sensitivity")
    op.drop_column("artifacts", "owner_user_id")
    op.drop_column("artifacts", "description")
    op.drop_column("artifacts", "kind_uri")
    op.drop_index("ix_grade_decisions_submission_created", table_name="grade_decisions")
    op.drop_index("ix_grade_decisions_proposal", table_name="grade_decisions")
    op.drop_table("grade_decisions")
    op.drop_table("message_parts")
    op.drop_index("ix_grade_proposals_submission_status", table_name="grade_proposals")
    op.drop_index(
        "ix_grade_proposals_producing_execution", table_name="grade_proposals"
    )
    op.drop_table("grade_proposals")
    op.drop_index("ix_artifact_parts_version_ordinal", table_name="artifact_parts")
    op.drop_table("artifact_parts")
    op.drop_index("ix_artifact_links_target", table_name="artifact_links")
    op.drop_index("ix_artifact_links_relationship", table_name="artifact_links")
    op.drop_table("artifact_links")
    op.drop_index("ix_messages_thread_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index(
        "ix_interaction_requests_execution_status", table_name="interaction_requests"
    )
    op.drop_table("interaction_requests")
    op.drop_table("execution_snapshots")
    op.drop_table("execution_legacy_refs")
    op.drop_index("ix_execution_events_type_time", table_name="execution_events")
    op.drop_index("ix_execution_events_trace", table_name="execution_events")
    op.drop_index("ix_execution_events_replay", table_name="execution_events")
    op.drop_table("execution_events")
    op.drop_index("ix_dispatch_outbox_claim", table_name="execution_dispatch_outbox")
    op.drop_table("execution_dispatch_outbox")
    op.drop_index("ix_artifact_versions_producer", table_name="artifact_versions")
    op.drop_index("ix_artifact_versions_artifact_state", table_name="artifact_versions")
    op.drop_table("artifact_versions")
    op.drop_index("ix_executions_thread_created", table_name="executions")
    op.drop_index("ix_executions_status_created", table_name="executions")
    op.drop_index("ix_executions_root_created", table_name="executions")
    op.drop_table("executions")
    op.drop_table("turns")
    op.drop_table("threads")
    op.drop_index("ix_flow_versions_published", table_name="flow_versions")
    op.drop_table("flow_versions")
    op.drop_index("ix_extension_grants_resolution", table_name="extension_grants")
    op.drop_table("extension_grants")
    op.drop_index("ix_flows_owner_archived", table_name="flows")
    op.drop_table("flows")
    op.drop_index(
        "ix_capability_definitions_lookup", table_name="capability_definitions"
    )
    op.drop_table("capability_definitions")
    op.drop_table("extension_installations")
    # ### end Alembic commands ###
