"""use_plugin_hash_as_pk

Revision ID: 39361b552edd
Revises: 20260203_0003
Create Date: 2026-02-10 10:48:55.275947
"""

from __future__ import annotations

from alembic import op  # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39361b552edd'
down_revision = '20260203_0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite does not support most ALTER COLUMN operations. 
    # Since these are just type refinements (NUMERIC -> UUID) that SQLite handles as strings anyway,
    # we skip them to avoid "near 'ALTER': syntax error".
    
    op.add_column('workflows', sa.Column('transcriber_plugin_hash', sa.Text(), nullable=True))
    op.add_column('workflows', sa.Column('grader_plugin_hash', sa.Text(), nullable=True))
    op.add_column('workflows', sa.Column('validator_plugin_hash', sa.Text(), nullable=True))
    
    # We use batch_alter_table for SQLite compatibility when dropping/adding constraints
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_workflows_transcriber_hash', 'plugins', ['transcriber_plugin_hash'], ['hash'])
        batch_op.create_foreign_key('fk_workflows_grader_hash', 'plugins', ['grader_plugin_hash'], ['hash'])
        batch_op.create_foreign_key('fk_workflows_validator_hash', 'plugins', ['validator_plugin_hash'], ['hash'])
        batch_op.drop_column('grader_plugin_id')
        batch_op.drop_column('validator_plugin_id')
        batch_op.drop_column('transcriber_plugin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcriber_plugin_id', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('validator_plugin_id', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('grader_plugin_id', sa.TEXT(), nullable=True))
        batch_op.drop_constraint('fk_workflows_transcriber_hash', type_='foreignkey')
        batch_op.drop_constraint('fk_workflows_grader_hash', type_='foreignkey')
        batch_op.drop_constraint('fk_workflows_validator_hash', type_='foreignkey')
        batch_op.drop_column('validator_plugin_hash')
        batch_op.drop_column('grader_plugin_hash')
        batch_op.drop_column('transcriber_plugin_hash')
    # ### end Alembic commands ###
