import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { hostGrotesk, remark } from "@/lib/fonts";
import "./globals.css";
import Header from "@/components/header";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fair Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} ${hostGrotesk.variable} ${remark.variable} font-sans antialiased pt-20 m-5`}
      >
        <Header
          user={{
            name: "Allan Zapata",
            email: "allan.zapata@up.ac.pa",
            initials: "AZ",
          }}
        />
        {children}
      </body>
    </html>
  );
}
